version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_net

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app_net

networks:
  app_net:

volumes:
  mongodb_data:
